apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-dpg-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
data:
  dpg.yaml: |
{{ include "dpg.renderConfig" (dict "config" .Values.dpgConfig "hosts" .Values.serviceHosts) | indent 4 }}
